<?php
/**
 * Created by PhpStorm.
 * User: voroninaleksandr
 * Date: 26.08.2018
 * Time: 11:48
 */

namespace Gora\DTO\Tests\Unit;

use Gora\DTO\Mappings\Property\PropertyCollection;
use Gora\DTO\Mappings\Property\PropertyInterface;

class PropertyCollectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PropertyInterface
     */
    private $properties;
    /**
     * @var PropertyCollection
     */
    private $propertyCollection;
    function setUp()
    {
        $this->propertyCollection = new PropertyCollection();
        $this->properties = array_fill(0,5,$this->getMockBuilder(PropertyInterface::class)->getMock());
        $this->assertCount(5,$this->properties);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetIterator()
    {
        foreach ($this->properties as $property) {
            $this->propertyCollection->add($property);
        }


        $this->assertInstanceOf(\ArrayIterator::class,$this->propertyCollection->getIterator());

        foreach ($this->propertyCollection as $item){
            $this->assertInstanceOf(PropertyInterface::class,$item);
            $this->assertContains($item,$this->properties);
        }
    }


    public function testAdd()
    {

        foreach ($this->properties as $property) {
            $this->propertyCollection->add($property);
            $this->assertContains($property,$this->propertyCollection->getIterator());
        }


    }
}
